### ISSUE TITLE
todo lists

### ISSUE THREAD

**Issue by zebernst** [neotron/SwiftBot-Discord#5]
- [ ] make the bot aware of discord roles in order to limit adding commands
- [ ] add proper help/long help support for builtin commands 
- [ ] fix long help for aliases
